#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/sports_db
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

